[package]
name = "fontspector-checkhelper"
version = "1.1.0"
edition = "2021"
description = "Macros for generating check functions for fontspector"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fonttools/fontspector"
homepage = "https://fonttools.github.io/fontspector"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.6"

[lints]
workspace = true
