# Ported from FontBakery profile fontwerk.py

# Included profiles
include_profiles = ["googlefonts"]

# Excluded checks
exclude_checks = ["googlefonts/canonical_filename", "googlefonts/family/italics_have_roman_counterparts", "googlefonts/font_copyright", "googlefonts/fstype", "googlefonts/gasp", "googlefonts/metadata/includes_production_subsets", "googlefonts/meta/script_lang_tags", "googlefonts/name/description_max_length", "googlefonts/name/line_breaks", "googlefonts/production_glyphs_similarity", "googlefonts/vendor_id", "googlefonts/version_bump", "fontdata_namecheck"]

[sections]
"Fontwerk Checks" = ["fontwerk/names_match_default_fvar", "fontwerk/style_linking", "fontwerk/vendor_id"]

# Configuration defaults

[configuration_defaults.file_size]
WARN_SIZE = 1048576
FAIL_SIZE = 9437184
