[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "fontspector"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

dependencies = [
    "fontTools",
    "fontbakery[all]>=0.13.0a3",
    "pytest",
]
[tool.maturin]
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"

