name: "Debug #119"

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ${{ matrix.os.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - build: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: macos-m1
            os: macos-latest
            target: aarch64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.os.target }}
          cache-key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Install protoc for lang repo
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.os.target }}
      - name: Test
        run: cargo run --release --target ${{ matrix.os.target }} -- fontspector-py/data/test/montserrat/* --html report.html
